#!/usr/bin/env bash

echo ""
echo "Running JustLikeTwitter console app"
echo "Use Ctrl-C to exit the program."
echo "Only sunny path cases have been covered."
echo ""
echo "Command-line help (usage with examples):"
echo ""
echo "  - Posting to personal timeline: <user name> -> <message>"
echo "  for e.g."
echo "     > Alice -> I'm having a great time"
echo ""
echo "  - Reading any user's timeline: <user name>"
echo "  for e.g."
echo "     > Alice "
echo "     I'm having a great time (2 seconds ago)"
echo ""
echo "  - Following another user: <user name> follows <another user>"
echo "  for e.g."
echo "     > Alice follows Bob"
echo ""
echo "  - Display user's wall : <user name> wall"
echo "  for e.g."
echo "     > Alice wall"
echo "     Bob - I'm in New York today! Anyone wants to have a coffee? (2 seconds ago)"
echo "     Alice - I'm having a great time (5 minutes ago)"
echo ""
echo ""
echo ""

sleep 2
mvn exec:java -Dexec.mainClass="interfaces.JustLikeTwitter"